import Background from "@/components/Background";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

// These styles apply to every route in the application
import Header from "@/components/Header";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body
        className="grid min-h-screen gap-2 px-8 py-6"
        style={{
          gridTemplateRows: "auto 1fr",
        }}
      >
        <Header />
        <Background />
        {children}
      </body>
    </html>
  );
}
